// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpussZKX_acgsWOvylipD_byKcG9IE7u0',
    appId: '1:365826461349:web:7b851c7c4a45e9cd0ec74c',
    messagingSenderId: '365826461349',
    projectId: 'flutter-test-ef74b',
    authDomain: 'flutter-test-ef74b.firebaseapp.com',
    storageBucket: 'flutter-test-ef74b.firebasestorage.app',
    measurementId: 'G-3SQCERHVHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBoKUk3jQwnTZqEKXTWUUr10ezsj6s5A4',
    appId: '1:365826461349:android:56795a959cb7db180ec74c',
    messagingSenderId: '365826461349',
    projectId: 'flutter-test-ef74b',
    storageBucket: 'flutter-test-ef74b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKM2aTs1DpFQREhAAAurhq8jKFAN10Ttw',
    appId: '1:365826461349:ios:b19476a9027556e00ec74c',
    messagingSenderId: '365826461349',
    projectId: 'flutter-test-ef74b',
    storageBucket: 'flutter-test-ef74b.firebasestorage.app',
    iosBundleId: 'com.example.newflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKM2aTs1DpFQREhAAAurhq8jKFAN10Ttw',
    appId: '1:365826461349:ios:b19476a9027556e00ec74c',
    messagingSenderId: '365826461349',
    projectId: 'flutter-test-ef74b',
    storageBucket: 'flutter-test-ef74b.firebasestorage.app',
    iosBundleId: 'com.example.newflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpussZKX_acgsWOvylipD_byKcG9IE7u0',
    appId: '1:365826461349:web:92442af1cb4444cf0ec74c',
    messagingSenderId: '365826461349',
    projectId: 'flutter-test-ef74b',
    authDomain: 'flutter-test-ef74b.firebaseapp.com',
    storageBucket: 'flutter-test-ef74b.firebasestorage.app',
    measurementId: 'G-753QM88VQ4',
  );

}